# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0003_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='headImg',
            field=models.ImageField(default=b'default.jpg', upload_to=b''),
        ),
    ]
